# Intro to NumPy

- Short for Numerical Python
- It is a fundamental library in the DS ecosystem
- It provides powerful tools for working with multidimensional arrays and matrices:
    - n-dimension arrays `ndarray`: core data structure. They offer efficient storage for various data types: strings, integers, floats, booleans, etc...
    - Array operations: a rich set of mathematical and statistical operations (functions)
    - Indexing, slicing, and merging or arrays
    - Linear Algebra concepts
    - Random array/matrix generation
- Advantages:
    - Performance and speed
    - IntegrationL it integrates easily with different DS modules, such as Pandas, Tensorflow, Schi-kit Learn, MatplotLib....
    - It's the foundation of so many DS libraries

## Basics

`pip install numpy`

> make sure you restart the kernel after installation 

In [98]:
import numpy as np

In [99]:
pip freeze

asttokens==3.0.0
colorama==0.4.6
comm==0.2.3
contourpy==1.3.3
cycler==0.12.1
debugpy==1.8.16
decorator==5.2.1
executing==2.2.0
fonttools==4.60.0
ipykernel==6.30.1
ipython==9.4.0
ipython_pygments_lexers==1.1.1
jedi==0.19.2
jupyter_client==8.6.3
jupyter_core==5.8.1
kiwisolver==1.4.9
matplotlib==3.10.6
matplotlib-inline==0.1.7
nest-asyncio==1.6.0
numpy==2.3.2
packaging==25.0
pandas==2.3.2
parso==0.8.4
pillow==11.3.0
platformdirs==4.3.8
prompt_toolkit==3.0.51
psutil==7.0.0
pure_eval==0.2.3
Pygments==2.19.2
pyparsing==3.2.5
python-dateutil==2.9.0.post0
pytz==2025.2
pywin32==311
pyzmq==27.0.1
scipy==1.16.2
seaborn==0.13.2
six==1.17.0
stack-data==0.6.3
tornado==6.5.2
traitlets==5.14.3
tzdata==2025.2
wcwidth==0.2.13
Note: you may need to restart the kernel to use updated packages.


In [100]:
# let's build our first array
arr = np.array([5,6,7])
arr

array([5, 6, 7])

In [101]:
type(arr)

numpy.ndarray

In [102]:
#convert a list into an array

my_list = [4,5,6,7,8,9]

arr = np.array(my_list)

print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


`arange()` function

In [103]:
list(range(0,21))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [104]:
np.arange(0,21) #sequence from 0 to 20

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [105]:
#fractional 
arr2 = np.arange(0,5.5,0.5)
arr2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [106]:
arr2.dtype

dtype('float64')

In [107]:
print('Num of dim:', arr2.ndim)
print('Array datatype:', arr2.dtype)

Num of dim: 1
Array datatype: float64


### Speed test between `ndarray` and `list`

In [108]:
import time

# Define the size of the data
size = 10**6

# Create a list and NumPy array with random data
list_data = list(range(size))
numpy_array = np.arange(size)

# Perform element-wise multiplication using a loop (for list)
start_time = time.time()
for i in range(size):
    list_data[i] *= 2
end_time = time.time()
list_time = end_time - start_time

# Perform element-wise multiplication using NumPy
start_time = time.time()
numpy_array *= 2
end_time = time.time()
numpy_time = end_time - start_time

print(f"Time taken for list: {list_time} seconds")
print(f"Time taken for NumPy array: {numpy_time} seconds")


Time taken for list: 0.2792820930480957 seconds
Time taken for NumPy array: 0.008679389953613281 seconds


## Array Dimensions

In [109]:
#0d array (scaler)
a0 = np.array(40)
a0.ndim

0

In [110]:
#1d array - vector/line
a1 = np.array([5,6,8])
a1.ndim

1

In [111]:
#2d array - matrix or table
a2 = np.array([[10,5,7],
               [12,7,15]])
a2.ndim

2

In [112]:
# get the num of rows and cols
#num of rows, num of cols
a2.shape

(2, 3)

In [113]:
a2.size #num of elements

6

In [114]:
a2 = np.array([[10,5,7],
               [12,7,np.nan]])

![im](https://miro.medium.com/v2/resize:fit:931/1*XIOuiEjfXAXOFa0-w2_pTw.jpeg)

In [115]:
a3 = np.array([[[5,6,7,8],
                [4,7,2,3],
                [5,8,0,3]
                ],#layer 2
                [[5,0,7,8],
                [1,8,2,1],
                [3,8,8,3]
                ],#layer 3
                [[5,6,7,8],
                [4,7,2,3],
                [4,7,2,3]
                ]
                ])

a3

array([[[5, 6, 7, 8],
        [4, 7, 2, 3],
        [5, 8, 0, 3]],

       [[5, 0, 7, 8],
        [1, 8, 2, 1],
        [3, 8, 8, 3]],

       [[5, 6, 7, 8],
        [4, 7, 2, 3],
        [4, 7, 2, 3]]])

In [116]:
a3.ndim

3

In [117]:
a3.shape #(layer, row, col)

(3, 3, 4)

In [118]:
print(f'This array has {a3.shape[0]} layers, {a3.shape[1]} rows, and {a3.shape[2]} columns')

This array has 3 layers, 3 rows, and 4 columns


## Arithmetic Operations in NumPy

In [119]:
arr1 = np.array([2,0,8])
arr2 = np.array([9,7,4])

In [120]:
arr1 + arr2

array([11,  7, 12])

In [121]:
arr1 * arr2

array([18,  0, 32])

#### Broadcasting 

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

In [122]:
arr1 = np.array([1,2,3]) #1d
arr2 = np.array(2) #0d

arr1 * arr2

array([2, 4, 6])

![bc](https://numpy.org/doc/stable/_images/broadcasting_1.png)

In [123]:
import numpy as np
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

![bc](https://numpy.org/doc/stable/_images/broadcasting_2.png)

In [125]:
b = np.array([1.0, 2.0, 3.0, 4.0])
a + b 

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

![m](https://numpy.org/doc/stable/_images/broadcasting_3.png)

In [126]:
b = np.array([[1.0], [2.0], [3.0], [4.0]]) #vertical 4-row array
a + b 

array([[ 1.,  1.,  1.],
       [12., 12., 12.],
       [23., 23., 23.],
       [34., 34., 34.]])

### Additional NumPy Functions

`reshape()`

In [127]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [128]:
#convert to a 2d array with 2x3 shape
arr_reshaped = arr.reshape(2,3)
arr_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
arr_reshaped.ndim

2

In [130]:
arr = np.arange(1,13)
arr.shape

(12,)

In [131]:
arr_3d = arr.reshape(2,2,3)
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [132]:
arr_3d.reshape(-1) #flatten the array regardless of size (back to 1 d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

`resize()` will force the array to take the specified shape

In [133]:
np.resize(arr,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

## Arrays with String Data Type

In [134]:
a = np.array(['a','b','c']) #U means unicode string
a

array(['a', 'b', 'c'], dtype='<U1')

In [135]:
greetings = np.array(['Hello', 'Welcome'])
subjects = np.array([' Learners', ' to the Class!'])

In [136]:
#to apply functions on strings we need to use char sub-module
np.char.add(greetings, subjects)

array(['Hello Learners', 'Welcome to the Class!'], dtype='<U21')

In [137]:
# concatenate function will merge the 2 lists with all elements independently
np.concatenate((greetings,subjects))

array(['Hello', 'Welcome', ' Learners', ' to the Class!'], dtype='<U14')

In [138]:
#text formatting
a = np.array(['Hello', 'hello', 'heLLo','HELLO', 'welCome','WELcome']) 
np.unique(a)

array(['HELLO', 'Hello', 'WELcome', 'heLLo', 'hello', 'welCome'],
      dtype='<U7')

In [139]:
a = np.char.upper(a)
a

array(['HELLO', 'HELLO', 'HELLO', 'HELLO', 'WELCOME', 'WELCOME'],
      dtype='<U7')

In [140]:
np.unique(a)

array(['HELLO', 'WELCOME'], dtype='<U7')

In [141]:
np.unique(a, return_counts=True)

(array(['HELLO', 'WELCOME'], dtype='<U7'), array([4, 2]))

**Exercise** Clean the array below (remove extra spaces) and make it consistent.

In [142]:
a = np.array([' Model A ', ' Model B ', ' Model C ', ' Concept D ', ' Concept E '])

In [143]:
a = np.char.replace(a, 'Model', 'Concept')
a

array([' Concept A ', ' Concept B ', ' Concept C ', ' Concept D ',
       ' Concept E '], dtype='<U11')

In [144]:
a = np.char.strip(a)
a

array(['Concept A', 'Concept B', 'Concept C', 'Concept D', 'Concept E'],
      dtype='<U11')

> for additional string functions, go to https://numpy.org/devdocs/reference/generated/numpy.char.chararray.html

In [145]:
# concat can glue 2 arrays together

arr1 = np.array([[10,20],
                 [5,8]])

arr2 = np.array([[6,0],
                 [1,9]])

np.concatenate((arr1,arr2), axis=0)

array([[10, 20],
       [ 5,  8],
       [ 6,  0],
       [ 1,  9]])

In [146]:
# to stitch them together side by side, use axis =1
np.concatenate((arr1,arr2), axis=1)

array([[10, 20,  6,  0],
       [ 5,  8,  1,  9]])

In [147]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [148]:
arr1 = np.array([[10,20],
                 [5,8]])
arr1

array([[10, 20],
       [ 5,  8]])

In [149]:
np.pad(arr1, pad_width=1)

array([[ 0,  0,  0,  0],
       [ 0, 10, 20,  0],
       [ 0,  5,  8,  0],
       [ 0,  0,  0,  0]])

In [150]:
np.resize(arr1, (4,4))

array([[10, 20,  5,  8],
       [10, 20,  5,  8],
       [10, 20,  5,  8],
       [10, 20,  5,  8]])

In [151]:
#transpose function
arr4 = np.array([[10,20,8],
                 [5,8,9]])

arr4.T

array([[10,  5],
       [20,  8],
       [ 8,  9]])

In [152]:
a3.T

array([[[5, 5, 5],
        [4, 1, 4],
        [5, 3, 4]],

       [[6, 0, 6],
        [7, 8, 7],
        [8, 8, 7]],

       [[7, 7, 7],
        [2, 2, 2],
        [0, 8, 2]],

       [[8, 8, 8],
        [3, 1, 3],
        [3, 3, 3]]])

### Statistical Functions 

In [153]:
# generate random array
arr = np.random.rand(1,10) #1d array with 10 elements
arr

array([[0.87742884, 0.75892108, 0.61532586, 0.79440381, 0.98733048,
        0.47596601, 0.39323838, 0.96473076, 0.240285  , 0.6340461 ]])

In [154]:
print(f'Array average: {np.mean(arr):.2f}')

Array average: 0.67


In [155]:
print(f'Array median: {np.median(arr)}')
print(f'Array standard deviation: {np.std(arr):.2f}')
print(f'Array maximum: {np.max(arr)}')

Array median: 0.6964835892963899
Array standard deviation: 0.24
Array maximum: 0.9873304779831676


In [156]:
a = np.array([[ 2.0,  7.0,  0.0],
              [12.0, 10.0, 19.0],
              [21.0, 25.0, 20.0],
              [40.0, 30.0, 32.0]])

np.mean(a) #a.mean()

np.float64(18.166666666666668)

![ax](https://www.sharpsightlabs.com/wp-content/uploads/2018/12/numpy-arrays-have-axes_updated_v2.png)

In [157]:
np.mean(a, axis=0)

array([18.75, 18.  , 17.75])

In [158]:
np.mean(a, axis=1)

array([ 3.        , 13.66666667, 22.        , 34.        ])

### Filtering in NumPy

In [159]:
arr = np.array([1,2,3,5,6,7,8,9,10,12,13,22,30,8,9,18])


In [160]:
# get the elements in the array that are less than 13
arr_filt = arr[arr<13]
arr_filt

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10, 12,  8,  9])

In [161]:
#multiple conditions
arr_filt = arr[(arr<13)&(arr>4)]
arr_filt

array([ 5,  6,  7,  8,  9, 10, 12,  8,  9])

Using `where()`

In [162]:
arr_filt = arr[np.where(arr>5)]
arr_filt

array([ 6,  7,  8,  9, 10, 12, 13, 22, 30,  8,  9, 18])

`where()` can work like the `IF()` in Excel

IF (condition, then, else)

In [163]:
arr

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10, 12, 13, 22, 30,  8,  9, 18])

In [164]:
np.where(arr>4, True, False)

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [165]:
np.where(arr>4, 'more than 4', 'less than 4')

array(['less than 4', 'less than 4', 'less than 4', 'more than 4',
       'more than 4', 'more than 4', 'more than 4', 'more than 4',
       'more than 4', 'more than 4', 'more than 4', 'more than 4',
       'more than 4', 'more than 4', 'more than 4', 'more than 4'],
      dtype='<U11')

In [166]:
np.where(arr>4, np.where(arr<20, 'less than 20', arr)
         , 'less than 4')

array(['less than 4', 'less than 4', 'less than 4', 'less than 20',
       'less than 20', 'less than 20', 'less than 20', 'less than 20',
       'less than 20', 'less than 20', 'less than 20', '22', '30',
       'less than 20', 'less than 20', 'less than 20'], dtype='<U21')

In [167]:
def square_val(x):
    return x ** 2

def double_val(x):
    return x * 2

In [168]:
np.where(arr>=10, double_val(arr), square_val(arr))

array([ 1,  4,  9, 25, 36, 49, 64, 81, 20, 24, 26, 44, 60, 64, 81, 36])

In [169]:
np.where(arr>=10, (lambda x: x-5)(arr), square_val(arr))

array([ 1,  4,  9, 25, 36, 49, 64, 81,  5,  7,  8, 17, 25, 64, 81, 13])

In [170]:
np.where((lambda x: x %2 == 0)(arr), 0, arr)

array([ 1,  0,  3,  5,  0,  7,  0,  9,  0,  0, 13,  0,  0,  0,  9,  0])

In [171]:
a = np.array([4,4,5,2,3,4])

org, dup_cnts = np.unique(a, return_counts=True)
dup = org[dup_cnts>1]
dup

array([4])

In [172]:
np.where(np.isin(a, dup), np.nan,a)

array([nan, nan,  5.,  2.,  3., nan])

In [173]:
a = np.array([[ 2.0,  7.0,  0.0],
              [12.0, 10.0, 19.0],
              [21.0, 25.0, 20.0],
              [40.0, 30.0, 32.0]])


**Exercise** if the num > 5, subtract 3, otherwise, leave it as is.

In [174]:
np.where(a>5,a-3,a)

array([[ 2.,  4.,  0.],
       [ 9.,  7., 16.],
       [18., 22., 17.],
       [37., 27., 29.]])

### Slicing and Dicing Using Indices

![ind](https://www.oreilly.com/api/v2/epubs/9781449323592/files/httpatomoreillycomsourceoreillyimages2172112.png)

In [175]:
a = np.array([[ 2.0,  7.0,  0.0],
              [12.0, 10.0, 19.0],
              [21.0, 25.0, 20.0]])


[row pos, col pos]

In [176]:
a[0,0]

np.float64(2.0)

In [177]:
a[2,1]

np.float64(25.0)

In [178]:
a[2] #3rd row

array([21., 25., 20.])

In [179]:
a[:,1] #2nd col

array([ 7., 10., 25.])

In [180]:
#ranges
a[1:] #last 2 rows

array([[12., 10., 19.],
       [21., 25., 20.]])

[row range, col range]

In [181]:
a[1:, 1:]

array([[10., 19.],
       [25., 20.]])

In [182]:
a[:2,1:]

array([[ 7.,  0.],
       [10., 19.]])

In [183]:
a = np.array([[ 2.0,  7.0,  0.0],
              [12.0, 10.0, 19.0],
              [21.0, 25.0, 20.0],
              [4   , 5   , 8   ]])


In [184]:
a[1:,1:]

array([[10., 19.],
       [25., 20.],
       [ 5.,  8.]])

In [185]:
a[:3,1]

array([ 7., 10., 25.])

In [186]:
a[1:3,1:]

array([[10., 19.],
       [25., 20.]])

In [187]:
a[:,1] = np.where(a[:,1]>7,8,a[:,1])
a

array([[ 2.,  7.,  0.],
       [12.,  8., 19.],
       [21.,  8., 20.],
       [ 4.,  5.,  8.]])

In [188]:
a[-1]

array([4., 5., 8.])

### Data Generation and Importing in NumPy

In [189]:
np.random.randint(low=1,high=55, size=40)

array([17, 13,  7, 30, 33, 53, 35,  9, 31, 54, 37, 41, 44,  2, 44, 21, 39,
       37, 42, 52, 40, 30, 53, 51, 54, 25, 35, 12, 40, 13, 12,  3, 27, 35,
       45, 36, 53,  2, 34, 22], dtype=int32)

In [190]:
np.random.randint(low=1,high=55, size=(10,10))

array([[46, 32, 53, 30, 38, 34, 36, 36, 45, 20],
       [ 8, 50, 22, 21, 24, 31, 38, 45, 33, 32],
       [38, 47, 25, 49, 17, 18, 14, 32, 52, 31],
       [38,  6, 38, 21,  9, 50, 31,  4, 12, 38],
       [ 1,  2, 45, 47,  3, 38, 41,  8, 52, 24],
       [ 7, 46, 25,  3, 42, 17, 16, 40, 39, 39],
       [25, 17, 54,  2, 29, 22, 16, 18, 24, 21],
       [18, 18, 15, 10,  4,  2, 46, 20, 49, 42],
       [36, 19, 54,  6, 50, 12, 24, 50, 33,  8],
       [16, 54, 27, 18, 38, 52, 19, 34, 22, 16]], dtype=int32)

In [191]:
# build a sequence betwee 2 numbers
# start, end, divisions
np.linspace(2,8,4)

array([2., 4., 6., 8.])

In [192]:
np.linspace(0,1,500)

array([0.        , 0.00200401, 0.00400802, 0.00601202, 0.00801603,
       0.01002004, 0.01202405, 0.01402806, 0.01603206, 0.01803607,
       0.02004008, 0.02204409, 0.0240481 , 0.0260521 , 0.02805611,
       0.03006012, 0.03206413, 0.03406814, 0.03607214, 0.03807615,
       0.04008016, 0.04208417, 0.04408818, 0.04609218, 0.04809619,
       0.0501002 , 0.05210421, 0.05410822, 0.05611222, 0.05811623,
       0.06012024, 0.06212425, 0.06412826, 0.06613226, 0.06813627,
       0.07014028, 0.07214429, 0.0741483 , 0.0761523 , 0.07815631,
       0.08016032, 0.08216433, 0.08416834, 0.08617234, 0.08817635,
       0.09018036, 0.09218437, 0.09418838, 0.09619238, 0.09819639,
       0.1002004 , 0.10220441, 0.10420842, 0.10621242, 0.10821643,
       0.11022044, 0.11222445, 0.11422846, 0.11623246, 0.11823647,
       0.12024048, 0.12224449, 0.1242485 , 0.12625251, 0.12825651,
       0.13026052, 0.13226453, 0.13426854, 0.13627255, 0.13827655,
       0.14028056, 0.14228457, 0.14428858, 0.14629259, 0.14829

### Importing text/csv files in NumPy

In [193]:
data = np.loadtxt('po_exam_prep.txt', delimiter=',', dtype=int)
data

ValueError: could not convert string 'Why do we use PI Objectives? - 85' to int64 at row 0, column 1.

> The syntax above works as the text file is in the same location as the notbook. If not, you need to specify the path

In [194]:
data = np.loadtxt('/document/po_exam_prepta.txt', delimiter=',', dtype=int)
data

FileNotFoundError: /document/po_exam_prepta.txt not found.

In [ ]:
data = np.genfromtxt('po_exam_prep.txt', delimiter=',', dtype=int)
data

ValueError: Some errors were detected !
    Line #9 (got 4 columns instead of 1)
    Line #17 (got 3 columns instead of 1)
    Line #26 (got 4 columns instead of 1)
    Line #31 (got 2 columns instead of 1)
    Line #36 (got 2 columns instead of 1)
    Line #40 (got 2 columns instead of 1)
    Line #42 (got 2 columns instead of 1)
    Line #43 (got 3 columns instead of 1)
    Line #56 (got 2 columns instead of 1)
    Line #68 (got 3 columns instead of 1)
    Line #86 (got 2 columns instead of 1)
    Line #94 (got 4 columns instead of 1)
    Line #103 (got 4 columns instead of 1)