Section 1
Data Analysis
1. Generate a matrix that shows daily temperature highs for two cities (City A & City B) over a week.
You need to generate a 2D NumPy array named temperatures with shape (7, 2). (temperatures between -10 and 30.
2. Print the average temperature of each city


In [13]:
temp = np.random.uniform(low=-10.0,high=30.0,size=(7,2))
temp=temp.round(2)
temp

array([[ 3.54, -6.39],
       [15.82, 28.22],
       [-3.2 , 26.61],
       [ 8.28, 14.69],
       [-6.91, 28.92],
       [-4.2 , -8.37],
       [25.5 , 12.77]])

In [41]:
#print(np.mean(temp, axis=0))
#print(f'The average temp in City A is {temp.mean(:,:1)} and the average temp in City B is {np.mean(temp, axis=0)}.')



#print("Temperature highs for the week (City A, City B):\n", temperatures)
# Step 3: Calculate average temperature for each city
average_temperatures = np.mean(temp, axis=0)

# Step 4: Print the average temperatures
print("\nAverage temperature for City A:", round(average_temperatures[0],2))
print("Average temperature for City B:", round(average_temperatures[1],2))


Average temperature for City A: 5.55
Average temperature for City B: 13.78


Section 2
Data Analysis
1. Plot Load num_data.csv file into an array
2. Get the shape
3. Reshape the matrix to a compatible (row,col) 2D matrix.
4. Define a new array that has values from the first array where number <10

In [55]:
numdataarr=np.loadtxt('num_data.csv',delimiter=",")
numdataarr

array([  9., 167.,  30.,  71., 102.,  87., 229., 227.,  91.,  78.,  84.,
       177.,  91.,  26., 226.,   7.,  92., 215., 185.,  86., 119., 191.,
        21., 182.,  53.,  70., 185., 129., 232.,  28., 106., 136.,  62.,
       168., 139., 154., 149., 125., 188.,  29., 180.,   7., 166., 228.,
        72.,  25., 114., 135.,  54., 208.,  33., 228., 125.,  82.,  69.,
        53., 218.,  90.,  52., 153., 101., 157., 160.,   9., 187.,  20.,
        93.,  42.,  65., 225.,  56.,  55.])

In [61]:
reshaped=np.reshape(numdataarr,(9,8))
print(reshaped.shape)
reshaped

(9, 8)


array([[  9., 167.,  30.,  71., 102.,  87., 229., 227.],
       [ 91.,  78.,  84., 177.,  91.,  26., 226.,   7.],
       [ 92., 215., 185.,  86., 119., 191.,  21., 182.],
       [ 53.,  70., 185., 129., 232.,  28., 106., 136.],
       [ 62., 168., 139., 154., 149., 125., 188.,  29.],
       [180.,   7., 166., 228.,  72.,  25., 114., 135.],
       [ 54., 208.,  33., 228., 125.,  82.,  69.,  53.],
       [218.,  90.,  52., 153., 101., 157., 160.,   9.],
       [187.,  20.,  93.,  42.,  65., 225.,  56.,  55.]])

Section 3
Data Analysis
1. Define the following array:
sales_data = np.array([
[50, 60, 55, 52, 60, 62, 65, 70, 75, 80, 85, 90], # Year 1
[95, 100, 110, 105, 115, 120, 125, 130, 140, 150, 160, 170] # Year 2
])
2. Calculate total sales of each year
3. Compute the difference in sales between Year 2 and Year 1 for each month.

In [66]:
sales = np.array([[50, 60, 55, 52, 60, 62, 65, 70, 75, 80, 85, 90], # Year 1
                  [95, 100, 110, 105, 115, 120, 125, 130, 140, 150, 160, 170]]) # year 2
sales

array([[ 50,  60,  55,  52,  60,  62,  65,  70,  75,  80,  85,  90],
       [ 95, 100, 110, 105, 115, 120, 125, 130, 140, 150, 160, 170]])

In [73]:
salestotal=np.sum(sales,axis=1)
salestotal
print(f'Year A sales equal {salestotal[0]} and Year B sales equal {salestotal[1]}')

Year A sales equal 804 and Year B sales equal 1520


In [76]:
print(sales[1]-sales[0])

[45 40 55 53 55 58 60 60 65 70 75 80]
